spring:
  application:
    name: ledger

  datasource:
    url: jdbc:postgresql://localhost:5432/ledger
    username: ledger
    password: ledger

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ledger-projector
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.sudesh.ledger.shared.event"
        spring.json.value.default.type: com.sudesh.ledger.shared.event.DomainEventEnvelope
      auto-offset-reset: earliest
      enable-auto-commit: false
    listener:
      ack-mode: manual

management:
  endpoints:
    web:
      exposure:
        include: health,info